import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, CheckCircle2, ChevronDown, GitBranch, Layers3, Play, RefreshCw, Search, Workflow } from 'lucide-react'
import { ontologyOperationsApi, type V2Action, type V2LogicRule } from '@/api/v2/ontologyOperations'

const pill = (status: string) => status === 'published' ? 'bg-green-50 text-green-700 border-green-200' : status === 'disabled' ? 'bg-gray-100 text-gray-500 border-gray-200' : 'bg-amber-50 text-amber-700 border-amber-200'

export default function OperationsTab({ ontologyId }: { ontologyId: string }) {
  const qc = useQueryClient()
  const [expanded, setExpanded] = useState<string | null>(null)
  const [message, setMessage] = useState('')
  const logic = useQuery({ queryKey: ['v2-logic', ontologyId], queryFn: () => ontologyOperationsApi.listLogic(ontologyId) })
  const actions = useQuery({ queryKey: ['v2-actions', ontologyId], queryFn: () => ontologyOperationsApi.listActions(ontologyId) })
  const machines = useQuery({ queryKey: ['state-machines', ontologyId], queryFn: () => ontologyOperationsApi.listStateMachines(ontologyId) })
  const mappings = useQuery({ queryKey: ['mappings', ontologyId], queryFn: () => ontologyOperationsApi.listMappings(ontologyId) })
  const runs = useQuery({ queryKey: ['action-runs', ontologyId], queryFn: () => ontologyOperationsApi.listRuns(ontologyId) })
  const refresh = () => { qc.invalidateQueries({ queryKey: ['v2-logic', ontologyId] }); qc.invalidateQueries({ queryKey: ['v2-actions', ontologyId] }); qc.invalidateQueries({ queryKey: ['action-runs', ontologyId] }); qc.invalidateQueries({ queryKey: ['mappings', ontologyId] }) }
  const mutate = useMutation({ mutationFn: (job: () => Promise<any>) => job(), onSuccess: (result: any) => { setMessage(result?.status || '操作完成'); refresh() }, onError: (error: any) => setMessage(error?.detail || error?.message || '操作失败') })
  const logicRows = logic.data ?? []
  const actionRows = actions.data ?? []
  const runRows = (runs.data as any[] | undefined) ?? []
  const allLoading = logic.isLoading || actions.isLoading
  const publish = (kind: 'logic' | 'actions') => mutate.mutate(kind === 'logic' ? () => ontologyOperationsApi.publishLogic(ontologyId) : () => ontologyOperationsApi.publishActions(ontologyId))
  const discover = (kind: 'logic' | 'actions') => mutate.mutate(kind === 'logic' ? () => ontologyOperationsApi.discoverLogic(ontologyId) : () => ontologyOperationsApi.discoverActions(ontologyId))

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div><h3 className="font-semibold text-gray-800">本体运行中心</h3><p className="text-sm text-gray-500 mt-1">统一查看 V2 规则、动作、状态机、映射和执行记录。</p></div>
      <button onClick={refresh} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-sm hover:bg-gray-50"><RefreshCw size={14} />刷新</button>
    </div>
    {message && <div className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-sm text-blue-700">{message}</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">
      {[['V2 规则', logicRows.length, GitBranch], ['V2 动作', actionRows.length, Play], ['状态机', machines.data?.length ?? 0, Workflow], ['映射', mappings.data?.length ?? 0, Layers3], ['动作运行', runRows.length, Activity]].map(([label, value, Icon]: any) => <div key={label as string} className="rounded-xl border bg-white p-4"><div className="flex justify-between text-sm text-gray-500"><span>{label}</span><Icon size={16} /></div><div className="mt-2 text-2xl font-semibold">{value}</div></div>)}
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-xl border bg-white p-5"><div className="mb-3 flex items-center justify-between"><div><h4 className="font-semibold">逻辑规则</h4><p className="text-xs text-gray-400">可发现、发布、审核和测试 V2 规则</p></div><div className="flex gap-2"><button onClick={() => discover('logic')} disabled={mutate.isPending} className="rounded border px-2 py-1 text-xs hover:bg-gray-50"><Search size={12} className="mr-1 inline" />发现</button><button onClick={() => publish('logic')} disabled={mutate.isPending} className="rounded bg-black px-2 py-1 text-xs text-white"><CheckCircle2 size={12} className="mr-1 inline" />发布</button></div></div>{allLoading ? <p className="py-6 text-center text-sm text-gray-400">加载中…</p> : logicRows.length === 0 ? <p className="py-6 text-center text-sm text-gray-400">暂无 V2 规则，可点击“发现”生成</p> : <div className="divide-y">{logicRows.map((rule: V2LogicRule) => <div key={rule.id} className="py-3"><button className="flex w-full items-center gap-2 text-left" onClick={() => setExpanded(expanded === rule.id ? null : rule.id)}><ChevronDown size={14} className={expanded === rule.id ? 'rotate-180' : ''} /><span className="flex-1 text-sm font-medium">{rule.name}</span><span className="text-xs text-gray-500">{rule.logic_type}</span><span className={`rounded border px-1.5 py-0.5 text-xs ${pill(rule.status)}`}>{rule.status}</span></button>{expanded === rule.id && <div className="mt-3 rounded-lg bg-gray-50 p-3 text-xs text-gray-600"><p>{rule.description || '暂无描述'}</p><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap">{JSON.stringify(rule.expression || {}, null, 2)}</pre><div className="mt-2 flex gap-2"><button onClick={() => mutate.mutate(() => ontologyOperationsApi.reviewLogic(ontologyId, rule.id, { status: rule.status === 'published' ? 'reviewed' : 'published' }))} className="rounded border bg-white px-2 py-1">更新状态</button><button onClick={() => mutate.mutate(() => ontologyOperationsApi.testLogic(ontologyId, rule.id, { row: {}, parameters: {} }))} className="rounded border bg-white px-2 py-1">测试空数据</button></div></div>}</div>)}</div>}</section>
      <section className="rounded-xl border bg-white p-5"><div className="mb-3 flex items-center justify-between"><div><h4 className="font-semibold">业务动作</h4><p className="text-xs text-gray-400">动作发布后才允许运行</p></div><div className="flex gap-2"><button onClick={() => discover('actions')} disabled={mutate.isPending} className="rounded border px-2 py-1 text-xs hover:bg-gray-50"><Search size={12} className="mr-1 inline" />发现</button><button onClick={() => publish('actions')} disabled={mutate.isPending} className="rounded bg-black px-2 py-1 text-xs text-white"><CheckCircle2 size={12} className="mr-1 inline" />发布</button></div></div>{allLoading ? <p className="py-6 text-center text-sm text-gray-400">加载中…</p> : actionRows.length === 0 ? <p className="py-6 text-center text-sm text-gray-400">暂无 V2 动作，可点击“发现”生成</p> : <div className="divide-y">{actionRows.map((action: V2Action) => <div key={action.id} className="py-3"><div className="flex items-center gap-2"><span className="flex-1 text-sm font-medium">{action.name}</span><span className="text-xs text-gray-500">{action.action_category}</span><span className={`rounded border px-1.5 py-0.5 text-xs ${pill(action.status)}`}>{action.status}</span><button title="执行动作" disabled={action.status !== 'published' || mutate.isPending} onClick={() => mutate.mutate(() => ontologyOperationsApi.runAction(ontologyId, action.id, { parameters: {} }))} className="rounded border p-1.5 hover:bg-gray-50 disabled:opacity-30"><Play size={13} /></button></div><p className="mt-1 text-xs text-gray-500">{action.description || '暂无描述'}</p></div>)}</div>}</section>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-xl border bg-white p-5"><h4 className="mb-3 font-semibold">状态机</h4>{(machines.data as any[] | undefined)?.length ? <div className="space-y-2">{(machines.data as any[]).map(m => <div key={m.id} className="rounded-lg border p-3"><div className="flex justify-between text-sm font-medium"><span>{m.entity_type_name}</span><span className="text-xs text-gray-500">状态属性：{m.state_property}</span></div><div className="mt-2 flex flex-wrap gap-1">{(m.states || []).map((s: any, i: number) => <span key={i} className="rounded-full bg-indigo-50 px-2 py-0.5 text-xs text-indigo-700">{typeof s === 'string' ? s : s.name || JSON.stringify(s)}</span>)}</div></div>)}</div> : <p className="text-sm text-gray-400">暂无状态机定义</p>}</section>
      <section className="rounded-xl border bg-white p-5"><h4 className="mb-3 font-semibold">映射与数据血缘</h4>{(mappings.data as any[] | undefined)?.length ? <div className="space-y-2">{(mappings.data as any[]).map(m => <div key={m.id || m.mapping_id} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><span className="flex-1"><b>{m.entity_class}</b><span className="ml-2 text-xs text-gray-500">← {m.dataset_name || '未命名数据集'}</span></span><span className={`rounded border px-1.5 py-0.5 text-xs ${pill(m.status)}`}>{m.status}</span><span className="text-xs text-gray-400">{m.confidence != null ? `${Math.round(m.confidence * 100)}%` : ''}</span></div>)}</div> : <p className="text-sm text-gray-400">暂无映射配置</p>}</section>
    </div>
    <section className="rounded-xl border bg-white p-5"><h4 className="mb-3 font-semibold">动作运行记录</h4>{runRows.length ? <div className="overflow-auto"><table className="min-w-full text-left text-xs"><thead className="bg-gray-50 text-gray-500"><tr><th className="px-3 py-2">时间</th><th className="px-3 py-2">目标对象</th><th className="px-3 py-2">状态</th><th className="px-3 py-2">错误</th></tr></thead><tbody>{runRows.map(run => <tr key={run.id} className="border-t"><td className="px-3 py-2">{run.started_at ? new Date(run.started_at).toLocaleString() : '-'}</td><td className="px-3 py-2">{run.target_object_id || '-'}</td><td className="px-3 py-2"><span className={`rounded border px-1.5 py-0.5 ${pill(run.status)}`}>{run.status}</span></td><td className="max-w-md truncate px-3 py-2 text-red-500">{run.error || '-'}</td></tr>)}</tbody></table></div> : <p className="text-sm text-gray-400">暂无运行记录</p>}</section>
  </div>
}
